
services:

  #Builds the frontend Docker image and creates the frontend microservice
  yolo-client:
    image: yolo-client:v1.0.0
    build: ./client
    container_name: yolo-client
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on: 
      - yolo-backend
    networks:
      - app-net

  #Builds the backend Docker image and creates the backend microservice
  yolo-backend:
    image: yolo-backend:v1.0.0
    build: ./backend
    container_name: yolo-backend
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "5000:5000"
    depends_on: 
      - app-ip-mongo
    networks:
      - app-net

  #Creates the database microservice
  app-ip-mongo:
    image: mongo:7.0.4
    container_name: app-mongo
    ports:
      - "24018:24018"
    networks:
      - app-net
    volumes:
      - type: volume
        source: app-mongo-data
        target: /data/db

#Creates the network infrastructure necessary for the containers to communicate with each other
networks:
  app-net:
    driver: bridge

#Creates a Docker volume that persists all the data stored in the database
volumes:
  app-mongo-data:
    driver: local