
services:

  #Builds the frontend Docker image and creates the frontend microservice
  yoloclient:
    image: yoloclient:v1.0.0
    build: ./client
    container_name: yoloclient
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on: 
      - yolobackend
    networks:
      - appnet

  #Builds the backend Docker image and creates the backend microservice
  yolobackend:
    image: yolobackend:v1.0.0
    build: ./backend
    container_name: yolobackend
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "5000:5000"
    depends_on: 
      - appipmongo
    networks:
      - appnet
    environment:
      MONGO_URL: mongodb://appipmongo:27018/yolomy

  #Creates the database microservice
  appipmongo:
    image: mongo:4.4.6
    container_name: mongodb_data
    ports:
      - "27018:27018"
    networks:
      - appnet
    volumes:
      - appmongodata:/data/db

#Creates the network infrastructure necessary for the containers to communicate with each other
networks:
  appnet:
    driver: bridge

#Creates a Docker volume that persists all the data stored in the database
volumes:
  appmongodata:
    driver: local