---
- name: Run MongoDB Container
  docker_container:
    name: appipmongo
    image: mongo:4.4.6
    ports:
      - '27017:27017'
    volumes:
      - ./appmongodata:/data/db
    networks:
      - name: appnet
  tags:
    - database
    - backend