apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolobackend
spec:
  selector:
    matchLabels:
      app: yolobackend
  template:
    metadata:
      labels:
        app: yolobackend
    spec:
      containers:
      - name: yolobackend-cont
        image: paulmaingi/yolobackend:v1.0.0
        resources:
          limits:
            memory: "2Gi"
            cpu: "500m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: yolobackend-serv
spec:
  type: LoadBalancer
  selector:
    app: yolobackend
  ports:
  - port: 5000
    targetPort: 5000
